apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: microservices-pipeline
  namespace: default
spec:
  tasks:
  - name: test-checkout
    taskRef:
      name: go-test
    params:
    - name: target
      value: ./src/checkoutservice./...
  - name: build-checkoutservice
    taskRef:
      name: build-push
    inputs:
    - name: workspace
      providedBy:
      - test-checkout
    params:
    - name: pathToDockerfile
      value: src/checkoutservice/Dockerfile