apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: kritis-pipeline-run-12321312984
  namespace: default
spec:
  pipelineRef:
    name: kritis-pipeline
  pipelineParamsRef:
    name: pipelineparams-sample
  triggerRef:
    type: manual
  resources:
  - name: unit-test-kritis
    inputs:
    - key: workspace
      resourceRef:
        name: kritis-resources-git
  - name: push-kritis
    inputs:
      - key: workspace
        resourceRef:
          name: kritis-resources-git
    outputs:
      - key: builtImage
        resourceRef:
          name: kritis-resources-image
  - name: deploy-test-env
    inputs:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    - name: builtImage
      resourceRef:
        name: kritis-resources-image
    - name: testCluster
      resourceRef:
        name: kritistestcluster
  - name: integration-test
    inputs:
    - name: workspace
      resourceRef:
          name: kritis-resources-git
