apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    knative.dev/pipeline: kritis-pipeline-run-12321312984
  name: unit-test-kritis-feature-x
spec:
    taskRef:
        name: make
    trigger:
        triggerRef:
            type: pipelineRun
            name: kritis-pipeline-run-1232131298422
    inputs:
        resourcesVersion:
          - resourceRef:
              name: kritis
            version: HEAD
        params:
            - name: 'makeTarget'
              type: 'string'
              value: 'test'
    results:
        runs:
          name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
        logs:
          name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
        tests:
          name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
status:
    steps:
    - name: make
      logsURL: 'gcs://somebucket/results/tests/unit-test-kritis-feature-x/make'
      exitCode: 0
    conditions:
    - type: Started
      status: "True"
      lastTransitionTime: "2018-10-04T12:25:39Z"
      reason: pipelineRun
      message: "Task has been triggered by a Pipeline run"
    - type: Completed
      status: "True"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: done
      message: "Pipeline execution has finished"
    - type: Successful
      status: "True"
      lastTransitionTime: "2018-10-04T13:25:39Z"
      reason: zeroExitCode
      message: "All steps completed with an exit code of 0"
