apiVersion: pipeline.knative.dev/v1alpha1
kind: TaskRun
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: unit-test-kritis-feature-x
spec:
  taskRef:
    name: make
  trigger:
    triggerRef:
      type: PipelineRun
      name: kritis-pipeline-run-12321312984
  inputs:
    resources:
    - name: workspace
      resourceRef:
        name: kritis-resources-git
    params:
    - name: 'makeTarget'
      value: 'test'