apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: microservices-pipeline
  namespace: default
spec:
    tasks:
      - name: build-productcatalog
        taskRef:
          name: build-push
        params:
          - name: pathToDockerfile
            value: src/productcatalogservice/Dockerfile
      - name: build-checkoutservice
        taskRef:
          name: build-push
        params:
          - name: pathToDockerfile
            value: src/checkoutservice/Dockerfile
      - name: build-frontend
        taskRef:
          name: build-push
        params:
          - name: pathToDockerfile
            value: src/frontend/Dockerfile
      - name: deploy-all
        taskRef:
          name: deploy-with-kubectl
        inputs:
          - name: workspace
            providedBy:
              - build-checkoutservice
              - build-productcatalog
              - build-frontend
          params:
              - name: pathToFiles
                value: kubernetes-manifests