apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: guarded-pr-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
      - name: check-file
        taskSpec:
          results:
            - name: exists
              description: indicates whether the file exists or is missing
          steps:
            - name: check-file
              image: alpine
              script: |
                printf yes | tee /tekton/results/exists
      - name: echo-file-missing
        when:
          - input: "$(tasks.check-file.results.exists)"
            operator: in
            values: ["missing"]
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: 'echo file missing'
    finally:
      - name: do-something-finally
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: 'echo finally done'
