apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineParams
metadata:
  name: pipelineparams-sample
  namespace: default
spec:
    serviceAccount: 'demoServiceAccount'
    clusters:
        - name: 'testCluster'
          type: 'gke'
          endpoint: 'https://prod.gke.corp.com'
        - name: 'stagingCluster'
          type: 'gke'
          endpoint: 'https://staging.gke.corp.com'
    results:
        runs:
          name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
        logs:
          name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
        tests:
          name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
    params:
    - name: resources.kritis-resources-git.url
      value: https://github.com/grafeas/kritis
    - name: resources.kritis-resources-git.revision
      value: master
    - name: resources.kritis-resources-test-git.url
      value: https://github.com/grafeas/kritis-test
    - name: resources.kritis-resources-image.url
      value: gcr.io/staging-image
    - name: resoruces.kritis-test-cluster.endpoint
      value: 'https://prod.gke.corp.com'
