apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: kritis-pipeline-run-12321312984
  namespace: default
spec:
    pipelineRef:
        name: kritis-pipeline
    triggerRef:
        type: manual
