apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: output-pipeline
  namespace: default
spec:
  tasks:
  - name: first-create-file          # 1. create file
    taskRef:
      name: create-file
  - name: then-check                 # 2.  check file exists
    taskRef:
      name: check-stuff-file-exists
    resources:
      - name: workspace
        providedBy: [first-create-file]