apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: guestbook-example
  namespace: default
spec:
  tasks:
  - name: build-guestbook
    taskRef:
      name: build-push
    params:
    - name: pathToDockerfile
      value: guestbook-go/Dockerfile
  - name: build-redis
    taskRef:
      name: build-push
    params:
    - name: pathToDockerfile
      value: 4/debian9/4.0/Dockerfile
  - name: deploy-bundle-test
    taskRef:
      name: deploy-with-kubectl
    resources:
    - name: imageToDeploy1
      providedBy:
      - build-redis
    - name: imageToDeploy2
      providedBy:
      - build-guestbook
    params:
    - name: pathToFiles
      value: guestbook/all-in-one/guestbook-all-in-one.yaml
  - name: int-test-osx
    resources:
    - name: workspace
      providedBy:
      - deploy-bundle-test
    params:
    - name: dockerBuildFile
      value: guestbook-int/Dockerfile
  - name: int-test-linux
    taskRef:
      name: integration-test-in-docker
    resources:
    - name: workspace
      providedBy:
      - deploy-bundle-test
    params:
    - name: dockerBuildFile
      value: guestbook-int/Dockerfile
  - name: deploy-bundle-test
    taskRef:
      name: deploy-with-kubectl
    resources:
    - name: redisImage
      providedBy:
      - int-test-osx
      - int-test-linux
    - name: guestbookImage
      providedBy:
      - int-test-osx
      - int-test-linux
    params:
    - name: pathToFiles
      value: guestbook/all-in-one/guestbook-all-in-one.yaml