apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: kritis-pipeline
  namespace: default
spec:
  tasks:
  - name: unit-test-kritis
    taskRef:
      name: make
    params:
    - name: makeTarget
      value: test
  - name: push-kritis
    taskRef:
      name: build-push
    resources:
      - name: workspace
        providedBy: [unit-test-kritis]
    params:
    - name: pathToDockerfile
      value: deploy/Dockerfile
  - name: deploy-test-env
    taskRef:
      name: deploy-with-helm
    resources:
    - name: builtImage
      providedBy: [push-kritis]
    params:
    - name: pathToHelmCharts
      value: kritis-charts
  - name: integration-test
    taskRef:
      name: integration-test-in-docker
    resources:
    - name: workspace
      providedBy: [deploy-test-env]
    params:
    - name: testArgs
      value: "-e REMOTE_INTEGRATION=true"
    - name: testCommand
      value: "make integration-in-docker"