apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: deploy-with-helm
  namespace: default
spec:
    inputs:
        resources:
              - name: workspace
                type: git
        params:
            - name: pathToHelmCharts
            - name: helmArgs
            - name: image
        clusters:
            - name: targetCluster
    buildSpec:
        steps:
        - name: deploy
          image: kubernetes-helm
          args: ['install', '--kube-context=${inputs.clusters.targetCluster}', '--set image=${inputs.params.image}', '${inputs.params.helmArgs}', '${inputs.params.pathToHelmChart}']
