apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: hello
  namespace: default
spec:
    buildSpec:
        steps:
            - name: hello
              image: "busybox"
              args: ['echo', 'see me never']
