apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
  namespace: default
spec:
  type: image
  params:
  - name: url
    value: us.gcr.io/christiewilson-catfactory/skaffold-leeroy-web

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-app
  namespace: default
spec:
  type: image
  params:
  - name: url
    value: us.gcr.io/christiewilson-catfactory/skaffold-leeroy-app