apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: kaniko
  namespace: default
spec:
    inputs:
        resources:
            - name: workspace
              type: git
        params:
            - name: pathToDockerfile
            - name: pathToContext
    outputs:
        resources:
            - name: builtImage
              type: image
    buildSpec:
          steps:
          - name: build-and-push
            image: gcr.io/kaniko-project/executor
            args:
            - --dockerfile=${inputs.params.pathToDockerfile} # TODO: This is wrong in all of our examples
            - --context=${inputs.params.pathToContext}
            - --destination=${outputs.resources.builtImage.url}
            # TODO: hack warning, service account should work
            volumeMounts:
            - name: kaniko-secret
              mountPath: /secret
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secret/config.json
              # TODO: this is where Build puts the service account's token, but that's not the format GOOGLE_APPLICATION_CREDENTIALS expects
              #value: /var/run/secrets/kubernetes.io/serviceaccount/token
          volumes:
          - name: kaniko-secret
            secret:
                secretName: skaffold-key # TODO: this is a total hack, should use service account instead
