apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: skaffold-pipeline
  namespace: default
spec:
    tasks:
        - name: build-skaffold-web
          taskRef:
              name: kaniko
          inputSourceBindings:
              - name: workspace
                key: workspace
                resourceRef:
                  name: skaffold
          outputSourceBindings:
              - name: image
                key: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-web
          params:
              - name: pathToDockerfile
                value: examples/microservices/leeroy-web/Dockerfile
        - name: build-skaffold-app
          taskRef:
              name: kaniko
          inputSourceBindings:
              - name: source
                key: workspace
                resourceRef:
                  name: skaffold
          outputSourceBindings:
              - name: image
                key: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-app
          params:
              - name: pathToDockerfile
                value: examples/microservices/leeroy-app/Dockerfile
