apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
  namespace: default
spec:
    tasks:
        - name: build-skaffold-web
          taskRef:
              name: kaniko
          inputSourceBindings:
              # TODO: these all seem to have to have the same name in order to work
              - name: workspace
                key: workspace
                resourceRef:
                  name: workspace
          outputSourceBindings:
              - name: image
                key: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-web
          params:
              - name: pathToDockerfile
                value: examples/microservices/leeroy-web/Dockerfile
              - name: pathToContext
                value: /workspace/examples/microservices/leeroy-web
        - name: build-skaffold-app
          taskRef:
              name: kaniko
          inputSourceBindings:
              - name: source
                key: workspace
                resourceRef:
                  name: skaffold
          outputSourceBindings:
              - name: image
                key: builtImage
                resourceRef:
                  name: skaffold-image-leeroy-app
          params:
              - name: pathToDockerfile
                value: examples/microservices/leeroy-app/Dockerfile
              - name: pathToContext
                value: /workspace/examples/microservices/leeroy-app
