apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: workspace # This is due to a bug where resources aren't getting passed along correctly
  namespace: default
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/bobcatfish/skaffold