apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineParams
metadata:
  name: pipelineparams-sample
  namespace: default
spec:
    serviceAccount: 'demoServiceAccount'
    results:
        runs:
          name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
        logs:
          name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
        tests:
          name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
    resources:
      - name: kritis-resources-git
        spec:
          type: git
          params:
          - name: url
            value: https://github.com/grafeas/kritis
          - name: revision
            value: master
      - name: kritis-resources-test-git
        spec:    
          type: git
          params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/grafeas/kritis-test  
      - name: kritis-resources-image
        spec:  
          type: image
          params:
          - name: url
            value: gcr.io/staging-image
      - name: kritis-test-cluster
        spec:  
          type: cluster
          params:
          - name: endpoint
            value: 'https://prod.gke.corp.com'   
      - name: kritis-staging-cluster
        spec:  
          type: cluster
          params:
          - name: endpoint
            value: 'https://staging.gke.corp.com'   

